// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxsciucelujernjjqerk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4c2NpdWNlbHVqZXJuampxZXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTQzMDIsImV4cCI6MjA2MjYzMDMwMn0.Gmx0Gr6ih4BW9MI-_7g8SbzJyNPp-RowKSqLSeSVlFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);